CREATE TABLE dq.DataIssueArchive
(
	ArchiveID INT IDENTITY( 1, 1) NOT NULL,
	StagingID INT NOT NULL,
	TableID INT NOT NULL,
	IssueID INT NOT NULL,
	BatchID INT NOT NULL,
	JobID INT NOT NULL,
	JobTaskID INT NOT NULL,
	SourceRowPK VARCHAR(MAX) NOT NULL,
	ColumnName VARCHAR(255) NOT NULL,
	[Value] VARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_DataIssueArchive PRIMARY KEY ( ArchiveID )
)
